name: Pyright Lint

on:
  push:
    branches:
      - beta
  pull_request:
    paths:
      - "nonebot/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/pyright.yml"
      - "pyproject.toml"
      - "pdm.lock"

jobs:
  pyright:
    name: Pyright Lint
    runs-on: ubuntu-latest
    concurrency:
      group: pyright-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          no-root: true

      - name: Install dependencies
        run: |
          pdm install
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
